FROM ibmfunctions/action-python-v3.7

RUN pip3 install  \
   --upgrade pip \
   ibm_db_sa \
   ibm-cos-sdk \
   ibm_cloud_sdk_core==1.5.1 \
   ibm_watson \
   pandas \
   python-dateutil \
   requests \
   PyPDF2 \
   fuzzywuzzy \
   python-Levenshtein \
   extract_msg \
   /Users/arun.wagle@ibm.com/IBM/Demos/Watson/clients/EverestRe/submission-git/submission/distarunwagle_submission_intake_utils-0.0.1-py3-none-any.whl
